# Generated by Django 6.0.6 on 2026-06-25 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the attar/perfume', max_length=255, verbose_name='Product Name')),
                ('slug', models.SlugField(blank=True, help_text='Auto-generated URL-friendly name. Leave blank to auto-fill.', max_length=255, unique=True, verbose_name='URL Slug')),
                ('image', models.ImageField(help_text='Main product photograph', upload_to='products/', verbose_name='Product Image')),
                ('description', models.TextField(help_text='Detailed description: scent notes, ingredients, longevity, etc.', verbose_name='Full Description')),
                ('short_description', models.CharField(blank=True, help_text='One-line summary shown on product cards in the catalog', max_length=300, verbose_name='Short Description')),
                ('price', models.DecimalField(decimal_places=2, help_text='Selling price in Indian Rupees', max_digits=10, verbose_name='Price (₹)')),
                ('stock', models.PositiveIntegerField(default=0, help_text='Number of units currently available', verbose_name='Stock Quantity')),
                ('is_featured', models.BooleanField(default=False, help_text='If checked, this product will appear in the homepage featured section', verbose_name='Featured on Homepage')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this product from the catalog without deleting it', verbose_name='Active / Visible')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date Added')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text="Recipient's full name for shipping", max_length=255, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('phone', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('address_line1', models.CharField(help_text='House/Flat No., Street Name', max_length=255, verbose_name='Address Line 1')),
                ('address_line2', models.CharField(blank=True, help_text='Area, Landmark (optional)', max_length=255, verbose_name='Address Line 2')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('state', models.CharField(max_length=100, verbose_name='State')),
                ('pincode', models.CharField(max_length=10, verbose_name='PIN Code')),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total amount customer should have paid via UPI', max_digits=10, verbose_name='Total Amount (₹)')),
                ('upi_transaction_id', models.CharField(help_text='Transaction reference number provided by the customer', max_length=100, verbose_name='UPI Transaction ID')),
                ('payment_screenshot', models.ImageField(blank=True, help_text='Optional screenshot of UPI payment uploaded by customer', null=True, upload_to='payment_screenshots/', verbose_name='Payment Screenshot')),
                ('status', models.CharField(choices=[('pending', 'Pending — Awaiting Payment Verification'), ('payment_received', 'Payment Received'), ('processing', 'Processing — Being Prepared'), ('shipped', 'Shipped — Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Order Status')),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes (not visible to customer)', verbose_name='Admin Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Order Placed On')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('customer', models.ForeignKey(blank=True, help_text='The registered user who placed this order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Customer Account')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('price', models.DecimalField(decimal_places=2, help_text='Stored at time of order — not affected by future price changes', max_digits=10, verbose_name='Unit Price at Purchase (₹)')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.order', verbose_name='Order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='store.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
            },
        ),
    ]
